### ISSUE TITLE
ICE when compiling with Rust 1.51

### ISSUE THREAD

**Issue by jamesmcm** [Morganamilo/aur-depends#1]
Hi,

Trying to update paru, I get the following ICE from this package:

```
Compiling aur-depends v0.13.0
error: internal compiler error: failed to process buffered lint here
   --> /home/archie/.cargo/registry/src/github.com-1ecc6299db9ec823/aur-depends-0.13.0/src/resolve.rs:842:13
    |
842 | /             debug!(
843 | |                 "cache_aur_pkgs_recursive {:?}",
844 | |                 pkgs.iter().map(|p| p.as_ref()).collect::<Vec<_>>()
845 | |             )
    | |_____________^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C linker-plugin-lto --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

I've never hit an ICE before, so I'm not sure what the best steps are for debugging.

**Comment by Morganamilo** [comment]
Yeah I've had that too and was hoping it would just go away, In the mean time I've just been compiling with stable instead of nightly.

**Comment by jamesmcm** [comment]
It's strange because if I build the aur-depends repo itself, it seems to build fine - even on nightly.

Seems related to https://github.com/rust-lang/rust/issues/71957#issuecomment-761606011

**Comment by Morganamilo** [comment]
It's commented out now. So compiles with nightly.

**Comment by jamesmcm** [comment]
Thanks! I'll close this for now.
